# DATASET MACROS
TRAIN_SPLIT_SIZE = 0.99
CORPUS_PATH = "data/animesubs.txt"

# MODELING MACROS
SEQ_LEN = 512
EMBEDDING_SIZE = 256
ATTN_HEAD_COUNT = 4
LAYER_NUM = 6

VAL_STEPS = 10
VAL_INTERVAL = 50

CHECKPOINT_INTERVAL = 5000

# TRAINING MACROS
BATCH_SIZE = 256
TOTAL_STEPS = 15000